#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

# Force FPE handling on - worst case.
export FOAM_SIGFPE=true
export FOAM_SETNAN=true

runApplication blockMesh
runApplication icoFoam

# -----------------------------------------------------------------------------
