#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory

# Parse arguments for library compilation
if [ -f $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments ]
then  . $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
fi

#------------------------------------------------------------------------------

wmake $targetType avalanche

#------------------------------------------------------------------------------
