name: OF1812-AD

on: [push, pull_request]

env:
  DOCKER_WORKING_DIR: '/home/dafoamuser/OpenFOAM/OpenFOAM-v1812-AD'
  DOCKER_MOUNT_DIR: '/home/dafoamuser/mount/OpenFOAM-v1812-AD'
  DOCKER_TAG: 'latest'

jobs:

  regresstion_tests:
    runs-on: ubuntu-18.04
    name: Regression tests
    steps:
    - uses: actions/checkout@v2
    - name: Create the docker container and run the tests
      run: |
        docker pull dafoam/opt-packages:${{env.DOCKER_TAG}}
        docker run -i -d -u dafoamuser --name regtest -v $GITHUB_WORKSPACE:${{env.DOCKER_MOUNT_DIR}} dafoam/opt-packages:${{env.DOCKER_TAG}} /bin/bash
        docker exec -i regtest /bin/bash -c "rm -rf ${{ env.DOCKER_WORKING_DIR}} && cp -r ${{env.DOCKER_MOUNT_DIR}} ${{env.DOCKER_WORKING_DIR}}"
        docker exec regtest sed -i 's/$HOME/$DAFOAM_ROOT_PATH/g' ${{env.DOCKER_WORKING_DIR}}/etc/bashrc
        docker exec regtest sed -i 's/export WM_CODI_AD_MODE=CODI_AD_FORWARD/export WM_CODI_AD_MODE=CODI_AD_REVERSE/g' ${{env.DOCKER_WORKING_DIR}}/etc/bashrc
        docker exec -i regtest /bin/bash -c "echo dafoamuser | sudo -S apt-get update && echo dafoamuser | sudo -S apt-get install -y build-essential flex bison cmake zlib1g-dev libboost-system-dev libboost-thread-dev libreadline-dev libncurses-dev libxt-dev qt5-default libqt5x11extras5-dev libqt5help5 qtdeclarative5-dev qttools5-dev libqtwebkit-dev freeglut3-dev libqt5opengl5-dev texinfo  libscotch-dev libcgal-dev gfortran swig wget git vim cmake-curses-gui libfl-dev apt-utils libibverbs-dev --no-install-recommends"
        docker exec -i regtest /bin/bash -c ". /home/dafoamuser/loadDAFoam.sh && cd ${{env.DOCKER_WORKING_DIR}} && source etc/bashrc && export WM_NCOMPPROCS=4 && ./Allwmake 2> log"
        docker exec -i regtest /bin/bash -c ". /home/dafoamuser/loadDAFoam.sh && cd ${{env.DOCKER_WORKING_DIR}} && source etc/bashrc && cd tests/simpleFoamAD && ./Allrun.sh"

